// export const roleMenus = {
//   OWNER: ["Dashboard", "Users", "Payments", "Risk", "Result"],
//   MOTHER: ["Dashboard", "Users", "Payments", "Risk"],
//   WHITELABEL: ["Dashboard", "Users", "Payments"],
//   SUPERADMIN: ["Dashboard", "Users", "Payments", "Risk"],
//   ADMIN: ["Dashboard", "Users", "Payments", "Risk", "Result"],
//   B2C_SUBADMIN: ["Dashboard", "Users"],
//   B2B_SUBADMIN: ["Dashboard", "Users"],
//   SUPER_AGENT: ["Dashboard", "Users"],
//   MASTER_AGENT: ["Dashboard", "Users"],
//   AGENT: ["Dashboard", "Users"],
//   USER: ["Dashboard"],
// };

export const roleMenus = {
  OWNER: [
    "Dashboard",
    "Users",
    "Downline List",
    "My Account",
    "My Report",
    "Bet List",
    "Live Bet",
    "Risk Management",
    "Banking",
    "Match Control",
    "Admin Setting",
    "Payment",
    "Result",
    "Withdraw Request",
  ],

  MOTHER: [
    "Dashboard",
    "Users",
    "Downline List",
    "My Account",
    "My Report",
    "Bet List",
    "Live Bet",
    "Risk Management",
    "Banking",
    "Match Control",
    "Admin Setting",
    "Payment",
    "Result",
    "Withdraw Request",
  ],

  WHITELABEL: [
    "Dashboard",
    "Users",
    "Downline List",
    "My Account",
    "My Report",
    "Bet List",
    "Live Bet",
    "Risk Management",
    "Banking",
    "Payment",
    "Result",
  ],

  SUPERADMIN: [
    "Dashboard",
    "Users",
    "Downline List",
    "My Account",
    "My Report",
    "Bet List",
    "Live Bet",
    "Risk Management",
    "Banking",
    "Payment",
    "Result",
  ],

  ADMIN: [
    "Dashboard",
    "Users",
    "Downline List",
    "My Account",
    "My Report",
    "Bet List",
    "Live Bet",
    "Risk Management",
    "Banking",
    "Payment",
    "Result",
    "Withdraw Request",
  ],

  B2C_SUBADMIN: [
    "Dashboard",
    "Users",
    "Downline List",
    "My Account",
    "My Report",
    "Bet List",
    "Banking",
  ],

  B2B_SUBADMIN: [
    "Dashboard",
    "Users",
    "Downline List",
    "My Account",
    "My Report",
    "Bet List",
    "Banking",
  ],

  SENIOR_AFFILIATE: [
    "Dashboard",
    "Users",
    "Downline List",
    "My Account",
    "My Report",
    "Banking",
  ],

  AFFILIATE: [
    "Dashboard",
    "Users",
    "Downline List",
    "My Account",
    "My Report",
    "Banking",
  ],

  SUPER_AGENT: [
    "Dashboard",
    "Users",
    "Downline List",
    "My Account",
    "My Report",
    "Bet List",
    "Banking",
  ],

  MASTER_AGENT: [
    "Dashboard",
    "Users",
    "Downline List",
    "My Account",
    "My Report",
    "Bet List",
    "Banking",
  ],

  AGENT: [
    "Dashboard",
    "Users",
    "Downline List",
    "My Account",
    "My Report",
    "Bet List",
    "Banking",
  ],

  USER: ["Dashboard", "My Account", "My Report", "Bet List", "Banking"],
};
